apiVersion: v1
kind: Service
metadata:
  name: wiremock-svc
  labels:
    type: mock
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000   # Specify the desired NodePort here
  selector:
    type: mock