apiVersion: v1
kind: PersistentVolume
metadata:
  name: jmeter-pv
  labels:
    type: local
spec:
  storageClassName: jmeter-pv
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/platform/data/three"

