---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: influxdb
  name: influxdb-pvc
spec:
  storageClassName: influxdb-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
