apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-config-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: influxdb-config-pv

#  awsElasticBlockStore:
 #   volumeID: vol-0e4359800d0fcf730    # Optionally specify an existing EBS volume ID
  #  fsType: ext4   # File system type
  hostPath:
    path: /data/influxdb
