apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-config-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: influxdb-config-pv
  resources:
    requests:
      storage: 10Gi

