apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb-config
data:
  influxdb.conf: |
    [meta]
      dir = "/var/lib/influxdb/meta"
    
    [data]
      dir = "/data/influxdb/data"
      engine = "tsm1"
      wal-dir = "/data/influxdb/wal"
